sudo: false
language: node_js
node_js:
  - stable

cache:
  bundle: true
  directories:
    - node_modules
script:
  - npm test
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master